---
title: "R Notebook"
output: html_notebook
---

+ Guiding Question (i.e., Research Question): Make a clear statement of a single guiding/research question that will drive your analysis.  It should be phrased as a question that you will try to investigate (i.e., it should have a question mark) 
+ Become acquainted with your data sources:
  + Where did you find them?
  + Who collected/maintains them?
  + When & Why were they originally collected?
  + What does a case represent in each data source, and how many total cases are available?
  + What are some of the variables that you plan to use
  + The R Notebook should include R code chunks & output as well as narrative (bullet list is fine at this stage) as you answer these questions
+ Explore intuition related to the research question
  + Create some informative plots and summary statistics 
  + Describe preliminary observations and intuition about the research question
+ TWO Data Sources (at least)
  + Primary data:  This is the main data source to be used in your investigation and it MUST NOT be loaded directly from an R package (but API's are fine for example). You should have many cases (e.g., at least hundreds--preferably many thousands), many variables including a mixture of both categorical & quantitative variables.  
  + Other data sources: No problem for these to come from an R package--for example, the ZipGeography or ZipDemography data (from DataComputing package) might be useful when joined with primary sources as you investigate some phenomenon in the US. 
  + Note: Each data source should be less than 80-100MB--the maximum file size permitted in a GitHub Repo... use sampling to create a reduced version for the purpose of the project if needed as we've done occasionally in exercises and weekly activities.